# Generated by Django 6.0.7 on 2026-08-29 00:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[('RELACIONADO_A', 'Relacionado a'), ('USA', 'Usa'), ('DEPENDE_DE', 'Depende de'), ('ORIGINOU', 'Originou'), ('INSPIROU', 'Inspirou'), ('PARTICIPA_DE', 'Participa de'), ('RESOLVE', 'Resolve'), ('RESPONDE', 'Responde'), ('AFETA', 'Afeta'), ('GEROU', 'Gerou'), ('APRENDEU_COM', 'Aprendeu com')], max_length=40)),
                ('origin_id', models.UUIDField()),
                ('target_id', models.UUIDField()),
                ('origin_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('target_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Relacionamento',
                'verbose_name_plural': 'Relacionamentos',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('origin_type', 'origin_id', 'target_type', 'target_id', 'type'), name='unique_relationship')],
            },
        ),
    ]
