# Generated by Django 6.0.7 on 2026-08-29 01:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('preferencia', 'Preferência'), ('contexto', 'Contexto'), ('objetivo', 'Objetivo'), ('projeto', 'Projeto'), ('decisao', 'Decisão'), ('experiencia', 'Experiência')], default='contexto', max_length=20)),
                ('content', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Memória',
                'verbose_name_plural': 'Memórias',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['owner', 'kind'], name='assistant_m_owner_i_533b09_idx')],
            },
        ),
    ]
