# Generated by Django 6.0.7 on 2026-08-29 11:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_toolproposal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('query', models.CharField(max_length=2000)),
                ('status', models.CharField(choices=[('running', 'Em execução'), ('done', 'Concluído'), ('error', 'Erro')], default='done', max_length=20)),
                ('iterations', models.PositiveIntegerField(default=1)),
                ('steps', models.JSONField(default=list)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Execução do agente',
                'verbose_name_plural': 'Execuções do agente',
                'ordering': ['-created_at'],
            },
        ),
    ]
