# Generated by Django 6.0.7 on 2026-08-29 01:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InboxItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Aberto'), ('classified', 'Classificado'), ('archived', 'Arquivado')], default='open', max_length=20)),
                ('kind', models.CharField(blank=True, max_length=40)),
                ('destination', models.CharField(blank=True, max_length=80)),
                ('summary', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item do Inbox',
                'verbose_name_plural': 'Itens do Inbox',
                'ordering': ['-created_at'],
            },
        ),
    ]
