# Generated by Django 6.0.7 on 2026-08-31 03:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('human', 'Humano'), ('service', 'Serviço')], default='human', max_length=20),
        ),
        migrations.CreateModel(
            name='ServiceCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('scopes', models.JSONField(blank=True, default=list, help_text="Escopos ('cognitive', 'events', ...).")),
                ('key_hash', models.CharField(editable=False, max_length=128)),
                ('key_hint', models.CharField(blank=True, max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credencial de serviço',
                'verbose_name_plural': 'Credenciais de serviço',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='accounts_se_user_id_6fa6c7_idx'), models.Index(fields=['key_hash'], name='accounts_se_key_has_b2a80b_idx')],
            },
        ),
    ]
